permalink: pretty
markdown: kramdown
include:
  - _pages
exclude:
  - ".rvmrc"
  - ".rbenv-version"
  - ".ruby-version"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "node_modules/"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
url: https://guides.railsgirls.org
source_url: https://github.com/railsgirls/railsgirls.github.io/blob/master/
plugins:
  - jekyll-redirect-from
site_title: "Rails Girls Guides"
default_page_description: "Learn how to make your own web apps with the Rails Girls guides."
